### ISSUE TITLE
Figure out a sane approach for all the various message types

### ISSUE THREAD

**Issue by atmos** [atmos/electrogram#5]
Slack sends oddly formatted responses which seem to indicate some parsing requirements need to be done client-side.

Images for example look like `<http://i.imgur.com/GwPfqZc.jpg>`, twitter, youtube, integraitons, etc are probably difficult.

**Comment by technicalpickles** [comment]
I started some work for this over in https://github.com/atmos/electrogram/pull/11 , but needs quite a bit of work.

From https://api.slack.com/docs/formatting : 

> URL detection is performed by the server. We do this so that URL detection (a non-trivial operation) is performed consistently across multiple clients

So all urls are going to have the `<http://whatever>` format, including images, twitter, youtube, etc

It's [unfurling](https://api.slack.com/docs/unfurling) that renders images as a real image, and seems we'd need to do that on the client side. I think you need to add a twitter integration to unfurl tweet URLs, but I'm not sure how that looks to a client yet.

Not sure how feasible or practical it is, but it might be super useful to have something capture as many of the different types of messages with something like https://github.com/linkedin/sepia and make it easy to replay them for development and testing.

**Comment by atmos** [comment]
I don't see anything wrt unfurling in the current slack client.

**Comment by atmos** [comment]
sepia looks ok but I always find it to be a pain in the ass to work with VCR sweets. Example payloads would obviously go a long way in testing the important types though.

**Comment by atmos** [comment]
It looks like we want to handle attachments. https://api.slack.com/docs/attachments

**Comment by atmos** [comment]
![welcome to slackhq 2015-06-29 19-28-33](https://cloud.githubusercontent.com/assets/38/8422794/1287182c-1e95-11e5-9d01-17b212181bd0.png)

So it looks like we need to process the attachments as regular images with different templates.
